/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Fri Aug 18 01:43:09 2017. */

#include "union.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MsgType1_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MsgType1, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgType2_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, MsgType2, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgType3_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MsgType3, value1, value1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, MsgType3, value2, value1, 0),
    PB_LAST_FIELD
};

const pb_field_t UnionMessage_fields[4] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, UnionMessage, msg1, msg1, &MsgType1_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, msg2, msg1, &MsgType2_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, msg3, msg2, &MsgType3_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(UnionMessage, msg1) < 65536 && pb_membersize(UnionMessage, msg2) < 65536 && pb_membersize(UnionMessage, msg3) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MsgType1_MsgType2_MsgType3_UnionMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(UnionMessage, msg1) < 256 && pb_membersize(UnionMessage, msg2) < 256 && pb_membersize(UnionMessage, msg3) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MsgType1_MsgType2_MsgType3_UnionMessage)
#endif


/* @@protoc_insertion_point(eof) */
